# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'component_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(822, 581)
        self.file_pushButton = QtWidgets.QPushButton(Form)
        self.file_pushButton.setGeometry(QtCore.QRect(140, 340, 151, 51))
        self.file_pushButton.setObjectName("file_pushButton")
        self.file_Edit = QtWidgets.QLineEdit(Form)
        self.file_Edit.setGeometry(QtCore.QRect(300, 340, 371, 41))
        self.file_Edit.setObjectName("file_Edit")
        self.confirm_pushButton = QtWidgets.QPushButton(Form)
        self.confirm_pushButton.setGeometry(QtCore.QRect(330, 420, 151, 91))
        self.confirm_pushButton.setObjectName("confirm_pushButton")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 70, 551, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.designator_Edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.designator_Edit.setObjectName("designator_Edit")
        self.horizontalLayout.addWidget(self.designator_Edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comment_Edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.comment_Edit.setObjectName("comment_Edit")
        self.horizontalLayout_2.addWidget(self.comment_Edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.file_pushButton.setText(_translate("Form", "Pin File"))
        self.confirm_pushButton.setText(_translate("Form", "Confirm"))
        self.label.setText(_translate("Form", "Designator："))
        self.label_2.setText(_translate("Form", "Comment："))
